server:
  port: 8080
  context-path: /produto

eureka:
  client:
    registryFetchIntervalSeconds: 3
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

teste: Tiago Teixeira profile

---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

server:
  port: 8080
  context-path: /produto
teste: Tiago Teixeira profile DOCKER  